version: "3"
services:
  server:
    build:
      context: ./server
    container_name: server2
    volumes:
      - ./server:/code
    ports:
      - "8201:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    stdin_open: true
    tty: true
  pgadmin:
    image: dpage/pgadmin4:4.19
    container_name: pgadmin2
    restart: always
    ports:
      - "8202:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
  postgres:
    image: postgres
    container_name: postgres2
    environment:
      POSTGRES_PASSWORD: notverysecret
