version: "3"
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/code
    ports:
      - "8100:8080"
  # server:
  #   build:
  #     context: ./server
  #   volumes:
  #     - ./server:/code
  #   ports:
  #     - "8101:5000"
  #   stdin_open: true
  #   tty: true
