version: "3"
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/code
    ports:
      - "8100:8080"
    depends_on:
      - mongo
  server:
    build:
      context: ./server
    volumes:
      - ./server:/code
    ports:
      - "8101:5000"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo-express:
    image: mongo-express
    ports:
      - "8102:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo
  pgadmin:
    image: dpage/pgadmin4:4.19
    container_name: pgadmin
    restart: always
    ports:
      - "8103:5050"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: notverysecret
