version: "3"
services:
  # client:
  #   build:
  #     context: ./client
  #   container_name: client3
  #   volumes:
  #     - ./client:/code
  #   ports:
  #     - "8300:8080"
  #   depends_on:
  #     - server
  # server:
  #   build:
  #     context: ./server
  #   container_name: server3
  #   volumes:
  #     - ./server:/code
  #   ports:
  #     - "8201:8000"
  #   command: python manage.py runserver 0.0.0.0:8000
  #   depends_on:
  #     - postgres
  #   stdin_open: true
  #   tty: true
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
  adminer:
    build:
      context: ./db_admin
    ports:
      - "8302:8080"
    depends_on:
      - db
