version: "3"
services:
  server:
    build:
      context: ./server
    container_name: server3
    volumes:
      - ./server:/code
    ports:
      - "8301:80"
    # depends_on:
    #   - db
    stdin_open: true
    tty: true
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
  adminer:
    build:
      context: ./db_admin
    ports:
      - "8302:8080"
    depends_on:
      - db
